# Generated by Django 3.0.2 on 2020-04-14 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcourse',
            name='course',
        ),
        migrations.AddField(
            model_name='examcourse',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='my_app.CategoryName'),
        ),
    ]
