# Generated by Django 3.0.2 on 2020-04-15 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200414_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateCollege',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.College')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.State')),
            ],
        ),
    ]
