# Generated by Django 3.0.2 on 2020-04-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_statecollege'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
