# Generated by Django 3.0.2 on 2020-04-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_college_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='addmission_status',
            field=models.IntegerField(default=0),
        ),
    ]
